//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriChem.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFeedback
    {
        public int Id { get; set; }
        public string ClientName { get; set; }
        public string ClientPosition { get; set; }
        public string Message { get; set; }
        public string ImageURL { get; set; }
        public string ClientName_Ar { get; set; }
        public string ClientPosition_Ar { get; set; }
        public string Message_Ar { get; set; }
    }
}
