//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriChem.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductImage = new HashSet<ProductImage>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public string TypicalApplication { get; set; }
        public string ProductFeatures { get; set; }
        public string Properties { get; set; }
        public string DataSheetPath { get; set; }
        public string CertificatePath { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string LinkId { get; set; }
        public string Title_Ar { get; set; }
        public string SubTitle_Ar { get; set; }
        public string Description_Ar { get; set; }
        public string TypicalApplication_Ar { get; set; }
        public string ProductFeatures_Ar { get; set; }
        public string Properties_Ar { get; set; }
        public string DataSheetPath_Ar { get; set; }
        public Nullable<int> Index { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImage { get; set; }
    }
}
